version: '3.3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  web:
    image: aaronfae/java-docker-compose:1.0
    ports:
      - 8080:8080
    depends_on:
      - redis